# Generated by Django 5.0.4 on 2024-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sight_height', models.FloatField(help_text='Height of the sight above the bore axis (inches)')),
                ('zero_distance', models.FloatField(help_text='Distance at which the weapon is zeroed (meters)')),
                ('twist', models.FloatField(help_text='Twist rate of the barrel (inches)')),
                ('zero_look_angle', models.FloatField(help_text='Angle of the sight line relative to the bore axis (degrees)')),
            ],
        ),
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(help_text='Length of the projectile (inches)')),
                ('mv', models.FloatField(help_text='Muzzle velocity (m/s)')),
                ('value', models.FloatField(help_text='Drag coefficient')),
                ('drag_table', models.TextField(choices=[('G1', 'G1'), ('G7', 'G7'), ('G2', 'G2'), ('G5', 'G5'), ('G6', 'G6'), ('G8', 'G8'), ('GI', 'GI'), ('GS', 'GS')], help_text='Drag table')),
                ('weight', models.FloatField(help_text='Weight of the projectile (grains)')),
                ('diameter', models.FloatField(help_text='Diameter of the projectile (inches)')),
                ('weapons', models.ManyToManyField(related_name='ammo', to='web.weapon')),
            ],
        ),
    ]
