# Generated by Django 5.0.4 on 2024-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammo',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
