# Generated by Django 5.0.4 on 2024-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_weapon_zero_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='zero_distance',
            field=models.FloatField(default=100, help_text='Distance at which the weapon is zeroed (meters)'),
            preserve_default=False,
        ),
    ]
