# Generated by Django 4.2.11 on 2024-06-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_weapon_zero_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=100)),
                ('color_r', models.IntegerField(default=255)),
                ('color_g', models.IntegerField(default=255)),
                ('color_b', models.IntegerField(default=255)),
                ('mode', models.TextField(choices=[('manual', 'MANUAL'), ('slow', 'AUTO: SLOW'), ('fast', 'AUTO: FAST')], default='manual', verbose_name='Rangefinder mode')),
                ('ammo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ammo')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.weapon')),
            ],
        ),
    ]
