# Generated by Django 4.2.11 on 2024-06-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_currentsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosshair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='crosshairs/')),
            ],
        ),
        migrations.AddField(
            model_name='currentsetting',
            name='plot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='currentsetting',
            name='crosshair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.crosshair'),
        ),
    ]
