# Generated by Django 4.2.11 on 2024-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_crosshair_currentsetting_plot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsetting',
            name='crosshair_size',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='currentsetting',
            name='crosshair_width',
            field=models.IntegerField(default=8),
        ),
    ]
